services:
  nginx:
    image: junmop950/jm-total-hub:react-latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Let's Encrypt 인증서 경로를 도커 컨테이너에 마운트
    ports:
      - "80:80"
      - "443:443"
